# Generated by Django 3.2.6 on 2021-08-23 05:50

from django.db import migrations, models

import helpers.random_name_generator


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_task_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="price_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="picture",
            field=models.ImageField(
                default=None,
                upload_to=helpers.random_name_generator.RandomFileName("items_blog"),
            ),
        ),
    ]
