# Generated by Django 3.2.6 on 2021-08-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20210823_0550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
